# Generated by Django 3.2.9 on 2021-11-16 21:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mirage.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prizes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('amount_left', models.IntegerField(blank=True, null=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raffle_id', models.TextField(validators=[django.core.validators.RegexValidator('^[a-f0-9]{8}-([a-f0-9]{4}-){3}[a-f0-9]{12}$')])),
                ('name', models.CharField(max_length=255)),
                ('total_tickets', models.IntegerField()),
                ('available_tickets', models.IntegerField(blank=True, null=True)),
                ('prizes', models.JSONField(blank=True, null=True)),
                ('remote_ip', models.GenericIPAddressField(choices=[('123.123.123.123', '123.123.123.123'), ('127.0.0.2', '127.0.0.2')])),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('winners_drawn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_number', models.IntegerField()),
                ('verification_code', mirage.fields.EncryptedCharField(blank=True, max_length=100, null=True)),
                ('has_won', models.BooleanField(default=False)),
                ('participant_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('participant_name', models.TextField(blank=True, null=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('winners_drawn', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='raffle_app.prizes')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='raffle_ticket', to='raffle_app.raffle')),
            ],
        ),
        migrations.AddField(
            model_name='prizes',
            name='raffle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='raffle_prize', to='raffle_app.raffle'),
        ),
    ]
